name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '1.8'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Diagnostic Logging
        run: |
          ls -la
          ls -la target
      - name: Build and push Docker image
        run: |
          docker build --no-cache -t ${{ secrets.ACR_SERVER_NAME }}.azurecr.io/table-management-image:${{ github.sha }} .
          docker push ${{ secrets.ACR_SERVER_NAME }}.azurecr.io/table-management-image:${{ github.sha }}

      #- name: Deploy to Azure Web App
      #  uses: azure/webapps-deploy@v2
       # with:
        #  app-name: '<your-azure-web-app-name>'
         # images: '<your-acr-name>.azurecr.io/table-management-image:${{ github.sha }}'
          #multi-container-config-type: 'compose'

